<?php	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center
	
	--------------Translate to chiness-------------
	Author: tomheng 
	Created: 2012-02-07
	Blog: http://blog.webfuns.net
	Git: git@github.com:tomheng/Question2Answer_zh.git
	------------------------------------------------	

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => '正在使用的工具:',
		'add_category_button' => '添加分类',
		'add_field_button' => '添加字段',
		'add_link_button' => '添加链接',
		'add_link_link' => ' - ^1添加链接^2',
		'add_new_field' => '添加新字段',
		'add_new_title' => '添加新标题',
		'add_page_button' => '添加页面',
		'add_title_button' => '添加标题',
		'add_widget_button' => '添加工具',
		'add_widget_link' => ' - ^1添加工具^2',
		'admin_title' => '管理中心',
		'after_footer' => '页脚链接之后',
		'after_main_menu' => '顶部所有选项卡之后',
		'after_x_tab' => '"^" 选项卡之后',
		'after_x' => '"^"之后',
		'moderate_title' => '审核',
		'basic_editor' => '初级编辑',
		'before_main_menu' => '顶部所有选项卡之前',
		'block_ips_note' => '用-表示范围，*表示任意数字。 示例: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => '用*匹配任意字母。示例: doh (仅匹配单词 doh) , doh* (匹配 doh 或者dohno) , do*h (匹配 doh, dooh, dough)。',
		'cancel_mailing_button' => '取消邮件发送',
		'categories_introduction' => '使用分类, 点击 \'添加分类\' 按钮。',
		'categories_not_shown' => '隐藏分类的问题不会被显示。',
		'categories_title' => '分类',
		'categories' => '分类',
		'category_add_sub' => '添加子分类',
		'category_added' => '已经添加的分类',
		'category_already_used' => '已经被使用',
		'category_default_slug' => 'category-^',
		'category_description' => '可添加分类描述:',
		'category_max_depth_x' => '分类层次不能超过 ^ 层。',
		'category_move_parent' => '修改父级分类',
		'category_name_first' => '第一个分类名称:',
		'category_name' => '分类名称:',
		'category_no_add_subs_x' => '分类层次超过 ^ 层无法添加子分类。',
		'category_no_delete_subs' => '存在子分类无法删除',
		'category_no_sub_error' => '^q 问题没有设置子分类  - ^1设置子分类^2',
		'category_no_sub_to' => '移动没有子分类的问题 ^ 到 :',
		'category_no_subs' => '空',
		'category_none_error' => '^q 问题没有分类 - ^1设置分类^2',
		'category_none_to' => '移动未分类的问题到:',
		'category_parent' => '父级分类:',
		'category_saved' => '保存分类',
		'category_slug' => '分类标识 - URL fragment:',
		'category_subs' => '子分类:',
		'category_top_level' => '无父级分类 (顶级)',
		'characters' => '字符',
		'check_language_suffix' => ' - ^1检查语言文件^2',
		'click_name_edit' => '自定义页面或链接:',
		'database_cleanup' => '清理数据库',
		'delete_category_reassign' => '删除该分类，并将该分类下所有问题转移至:',
		'delete_category' => '删除此分类',
		'delete_field' => '删除此字段',
		'delete_hidden_complete' => '所有隐藏的，并且没有关联的主题已被删除',
		'delete_hidden_note' => ' - 删除所有没有关联的问题、回复和评论',
		'delete_hidden' => '删除所有隐藏问题',
		'delete_link' => '删除此链接',
		'delete_page' => '删除此页面',
		'delete_stop' => '停止删除',
		'delete_title' => '删除该头衔',
		'delete_widget_position' => '删除在这的这个工具',
		'edit_custom_page' => '编辑自定义页面',
		'edit_field' => ' - ^1编辑字段^2',
		'edit_link' => ' - ^1编辑链接^2',
		'edit_page' => ' - ^1编辑页面^2',
		'edit_title' => ' - ^1编辑标题^2',
		'emails_per_minute' => '邮件发送频率',
		'emails_title' => '邮件',
		'feed_link_example' => '示例feed',
		'feed_link' => 'Feed',
		'feeds_title' => 'RSS feeds',
		'field_link_url' => '链接地址',
		'field_multi_line' => '多行文本',
		'field_name' => '字段名:',
		'field_single_line' => '单行文本',
		'field_type' => '字段类型:',
		'first' => '第一个',
		'flagged_title' => '标记',
		'from_anon' => '来自匿名用户:',
		'from_users' => '来自用户:',
		'general_title' => '基本设置',
		'hidden_answers_deleted' => '已删除^1 条，共 ^2 条隐藏回复...',
		'hidden_comments_deleted' => '已删除^1条，共 ^2 条隐藏评论...',
		'hidden_questions_deleted' => '已删除^1条，共 ^2 条无关连的隐藏提问...',
		'hotness_factors' => '问题热度:',
		'hidden_title' => '隐藏',
		'installed_plugins' => '已安装的插件:',
		'ip_address_pages' => 'IP 地址页面',
		'layout_title' => '布局',
		'link_name' => '链接文本:',
		'link_new_window' => '新窗口打开链接',
		'link_url' => '链接- 绝对地址或者相对根目录的地址:',
		'lists_title' => '列表',
		'mailing_complete' => '邮件已发送',
		'mailing_explanation' => '用户可以在帐号设置中取消订阅。',
		'mailing_progress' => '已发送^1用户，共^2用户...',
		'mailing_title' => '邮件发送',
		'mailing_unsubscribe' => '每条信息的页脚都会有一个退订链接。',
		'maintenance_admin_only' => '您的网站正在^1维护^2，普通用户无法访问。',
		'maximum_x' => ' (最大^)',
		'module_x_database_init' => ' ^1 ^2 模块 ^3数据库初始化^4.',
		'most_flagged_title' => '标识问题',
		'mysql_version' => 'MySQL 版本:',
		'nav_links_explanation' => '显示为导航链接:',
		'nav_qa_is_home' => 'Q&A (作为首页链接)',
		'neat_urls_note' => ' (须要支持 ^1htaccess^2 文件)',
		'no_approve_found' => '没有须要审核的内容',
		'no_classification' => '无分类',
		'no_flagged_found' => '没有标识内容',
		'no_hidden_found' => '没有隐藏内容',
		'no_image_gd' => '服务器PHP版本不支持GD扩展，用户无法上传头像。',
		'no_link' => '无链接',
		'no_multibyte' => '服务器的 PHP 没有多字节支持 (mbstring)，搜索非罗马字符的时候可能会有问题。',
		'no_plugin_options' => '已安装的插件没有设置选项。',
		'no_privileges' => '仅管理员可以访问本页面。',
		'not_logged_in' => '请以管理员帐号 ^1登录^2 访问。',
		'opposite_main_menu' => '标签右侧',
		'options_reset' => '已恢复默认设置',
		'options_saved' => '设置已保存',
		'options' => '选项',
		'page_already_used' => '页面已使用',
		'page_content_html' => '页面内容 - 支持HTML:',
		'page_default_slug' => 'page-^',
		'page_heading' => '页面顶部内容:',
		'page_name' => '页面名称 (用户标签和链接):',
		'page_slug' => '页面标识 (出现在链接中):',
		'pages_explanation' => '点击 \'添加页面\' 按钮添加自定义页面,或点击\'添加链接\' 到已存在的页。',
		'pages_title' => '页面',
		'pause_mailing_button' => '停止发送邮件',
		'per_ip_hour' => 'per IP/hour',
		'per_user_hour' => 'per user/hour',
		'permissions_title' => 'Permissions',
		'permit_to_view' => 'Visible for:',
		'php_version' => 'PHP version:',
		'pixels' => 'pixels',
		'plugin_module' => ' (plugin module: ^)',
		'plugin_pages_explanation' => 'Pages available via plugins:',
		'plugins_title' => 'Plugins',
		'points_defaults_shown' => 'Defaults shown below but NOT YET APPLIED:',
		'points_required' => 'Points required to receive title:',
		'points_title' => 'Points',
		'points' => 'points',
		'position' => 'Position:',
		'posting_title' => 'Posting',
		'profile_fields' => 'Extra fields on user profile:',
		'q2a_build_date' => 'Build date:',
		'q2a_db_size' => 'Database size:',
		'q2a_db_version' => 'Q2A database version:',
		'q2a_latest_version' => 'Latest version:',
		'q2a_version' => 'Question2Answer version:',
		'question_lists' => 'Question lists',
		'question_pages' => 'Question pages',
		'recalc_categories_backpaths' => 'Recalculating URL paths for ^1 of ^2 categories...',
		'recalc_categories_complete' => 'All categories were successfully recalculated.',
		'recalc_categories_note' => ' - for post categories and category counts',
		'recalc_categories_recounting' => 'Recounting questions for ^1 of ^2 categories...',
		'recalc_categories_updated' => 'Recalculated for ^1 of ^2 posts...',
		'recalc_categories' => 'Recalculate categories',
		'recalc_points_complete' => 'All user points were successfully recalculated.',
		'recalc_points_note' => ' - for user ranking and points displays',
		'recalc_points_recalced' => 'Recalculated for ^1 of ^2 users...',
		'recalc_points_usercount' => 'Estimating total number of users...',
		'recalc_points' => 'Recalculate user points',
		'recalc_posts_count' => 'Getting total number of questions, answers and comments...',
		'recalc_stop' => 'Stop recalculating',
		'recent_approve_title' => 'Recent content waiting for approval',
		'recent_hidden_title' => 'Recent hidden content',
		'recount_posts_as_recounted' => 'Recounted answers and hotness for ^1 of ^2 posts...',
		'recount_posts_complete' => 'All posts were successfully recounted.',
		'recount_posts_note' => ' - the number of answers, votes, flags and hotness for each post',
		'recount_posts_stop' => 'Stop recounting',
		'recount_posts_votes_recounted' => 'Recounted votes and flags for ^1 of ^2 posts...',
		'recount_posts' => 'Recount posts',
		'refill_events_complete' => 'All events streams were successfully refilled',
		'refill_events_note' => ' - for each user\'s list of updates',
		'refill_events_refilled' => 'Refilled for ^1 of ^2 questions...',
		'refill_events' => 'Refill event streams',
		'reindex_content' => 'Reindex content',
		'reindex_content_note' => ' - for searching and related question suggestions',
		'reindex_content_stop' => 'Stop reindexing',
		'reindex_pages_reindexed' => 'Reindexed ^1 of ^2 pages...',
		'reindex_posts_complete' => 'All posts were successfully reindexed.',
		'reindex_posts_reindexed' => 'Reindexed ^1 of ^2 posts...',
		'reindex_posts_wordcounted' => 'Recounted ^1 of ^2 words...',
		'requires_php_version' => 'Disabled - requires PHP ^ or later',
		'requires_q2a_version' => 'Disabled - requires Question2Answer ^ or later',
		'reset_options_button' => 'Reset to Defaults',
		'resume_mailing_button' => 'Resume Mailing',
		'save_options_button' => 'Save Options',
		'save_recalc_button' => 'Save and Recalculate',
		'send_test_button' => 'Send Test to Me',
		'show_defaults_button' => 'Show Defaults',
		'slug_bad_chars' => 'The slug may not contain these characters: ^',
		'slug_reserved' => 'This slug is reserved for use by another page',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Start Mailing',
		'stats_title' => 'Stats',
		'stop_recalc_warning' => 'A database clean-up operation is running. If you close this page now, the operation will be interrupted.',
		'tag_pages' => 'Tag pages',
		'tags_and_categories' => 'Tags and Categories',
		'tags_not_shown' => 'Some questions have tags which will not be displayed.',
		'tags' => 'Tags',
		'test_sent_to_x' => 'The test message was sent to ^',
		'title_already_used' => 'This value is already being used by another title',
		'top_level_categories' => 'Top level categories:',
		'total_as' => 'Total answers:',
		'total_cs' => 'Total comments:',
		'total_qs' => 'Total questions:',
		'unnamed_plugin' => 'Unnamed Plugin',
		'upgrade_db' => 'Your Question2Answer database needs to be ^1upgraded^2 for this version.',
		'url_format_note' => 'Options with the ^ label are working for your site\'s configuration. For best search engine optimization (SEO), use the first ^ option available.',
		'user_pages' => 'User pages',
		'user_title' => 'User title - HTML allowed:',
		'user_titles' => 'User titles based on points:',
		'users_active' => 'Active users:',
		'users_must_have' => 'Users must have',
		'users_posted' => 'Users who posted:',
		'users_registered' => 'Registered users:',
		'users_title' => 'Users',
		'users_voted' => 'Users who voted:',
		'version_get_x' => 'get ^',
		'version_latest_unknown' => 'latest unknown',
		'version_latest' => 'latest',
		'viewing_title' => 'Viewing',
		'widget_all_pages' => 'Show widget in this position on all available pages',
		'widget_global_options' => ' - ^1options^2',
		'widget_name' => 'Name of widget:',
		'widget_no_positions' => 'This widget has already been added to every available position.',
		'widget_not_available' => 'This widget is not available. This could be because the plugin providing the widget is no longer installed.',
		'widget_pages_explanation' => 'Show widget in this position on the following pages:',
		'widgets_explanation' => 'Available widgets:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
