<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A

	--------------Translate to chiness-------------
	Author: tomheng 
	Created: 2012-02-08
	Blog: http://blog.webfuns.net
	Git: git@github.com:tomheng/Question2Answer_zh.git
	------------------------------------------------	

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1个回复',
		'1_comment' => '1个评论',
		'1_day' => '1天',
		'1_disliked' => '1个人不喜欢',
		'1_flag' => '1举报',
		'1_hour' => '1小时',
		'1_liked' => '1个喜欢',
		'1_minute' => '1分钟',
		'1_month' => '1个月',
		'1_point' => '1积分',
		'1_question' => '1个问题',
		'1_second' => '1秒',
		'1_tag' => '1标签',
		'1_user' => '1用户',
		'1_view' => '1阅读',
		'1_vote' => '1投票',
		'1_week' => '1周',
		'1_year' => '1年',
		'add_category_x_favorites' => '收藏^分类',
		'add_favorites' => '收藏',
		'add_tag_x_favorites' => '收藏^标签',
		'all_categories' => '所有分类',
		'anonymous' => '匿名用户',
		'answer_edited' => '回复修改于',
		'answer_reshown' => '取消隐藏',
		'answer_selected' => '选中的回复',
		'answered_qs_in_x' => '^下最多回复问题',
		'answered_qs_title' => '最多回复问题',
		'answered' => '已回复',
		'asked_related_q' => '相似提问',
		'asked' => '时间:',
		'by_x' => '作者:^',
		'cancel_button' => '取消',
		'closed' => '关闭',
		'comment_edited' => '评论修改于',
		'comment_moved' => '评论移动到',
		'comment_reshown' => '取消隐藏',
		'commented' => '已评论',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^year年 ^month ^day日',
		'date_format_this_year' => '^month ^day日',
		'date_month_1' => '1月',
		'date_month_2' => '2月',
		'date_month_3' => '3月',
		'date_month_4' => '4月',
		'date_month_5' => '5月',
		'date_month_6' => '6月',
		'date_month_7' => '7月',
		'date_month_8' => '8月',
		'date_month_9' => '9月',
		'date_month_10' => '10月',
		'date_month_11' => '11月',
		'date_month_12' => '12月',
		'date_year_digits' => 4, // 2 or 4
		'edited' => '编辑',
		'field_required' => '请填写字段内容',
		'general_error' => '服务器出错 - 请重试.',
		'hidden' => '隐藏',
		'highest_users' => '积分排行',
		'hot_qs_in_x' => '^的热门问题',
		'hot_qs_title' => '热门问题',
		'image_not_read' => '图片无法显示，请上传一张: ^',
		'image_too_big_x_pc' => '图片太大，请修改到^%再重试一次',
		'in_category_x' => '分类:^',
		'ip_address_x' => 'IP地址 ^',
		'logged_in_x' => '你好^',
		'max_length_x' => '字符最多^',
		'me' => 'me',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => '字符数不能少于^个',
		'moved' => '移动到',
		'nav_account' => '我的帐号',
		'nav_activity' => '所有动态',
		'nav_admin' => '管理',
		'nav_ask' => '提问',
		'nav_categories' => '分类',
		'nav_feedback' => '反馈',
		'nav_home' => '首页',
		'nav_hot' => '热门!',
		'nav_login' => '登录',
		'nav_logout' => '退出',
		'nav_most_answers' => '回复最多',
		'nav_most_recent' => '最近',
		'nav_most_views' => '查看最多',
		'nav_most_votes' => '投票最多',
		'nav_no_answer' => '待回答',
		'nav_no_selected_answer' => '待解决',
		'nav_no_upvoted_answer' => '无赞成',
		'nav_qa' => 'Q&A',
		'nav_qs' => '问题',
		'nav_register' => '注册',
		'nav_tags' => '标签',
		'nav_unanswered' => '待回复',
		'nav_updates' => '我的更新',
		'nav_users' => '用户',
		'no_active_users' => '没有活跃用户',
		'no_answers_found' => '没有回复',
		'no_answers_in_x' => '^没有回复',
		'no_categories_found' => '没有找到分类',
		'no_category' => '没有分类',
		'no_comments_found' => '没有评论',
		'no_comments_in_x' => '^下没有评论',
		'no_questions_found' => '没有问题',
		'no_questions_in_x' => '^下没有提问',
		'no_related_qs_title' => '没有相关问题',
		'no_results_for_x' => '^未发现结果',
		'no_tags_found' => '没有标签',
		'no_una_questions_found' => '所有问题都已回答',
		'no_una_questions_in_x' => ' ^下没有未回答的问题',
		'no_unselected_qs_found' => '没有最佳答案的问题',
		'no_unupvoteda_qs_found' => '所有问题都有了赞成票',
		'page_label' => '页:',
		'page_next' => '下一页',
		'page_not_found' => '没有找到',
		'page_prev' => '前一页',
		'popular_tags' => '最受欢迎标签',
		'questions_tagged_x' => '^标签最近问题',
		'recategorized' => '重新设置分类',
		'recent_activity_in_x' => '^最新动态',
		'recent_activity_title' => '最近动态',
		'recent_as_in_x' => '^最近回复问题',
		'recent_as_title' => '最近被回复的问题',
		'recent_cs_in_x' => '^下的最新',
		'recent_cs_title' => '最近评论',
		'recent_qs_as_in_x' => '^下最近提问和回复',
		'recent_qs_as_title' => '最近提问和回复',
		'recent_qs_in_x' => '^下最近提问',
		'recent_qs_title' => '最近提问',
		'related_qs_title' => '相关问题',
		'remove_favorites' => '从收藏中删除',
		'remove_x_favorites' => '闪存^收藏',
		'reopened' => '重新打开',
		'reshown' => '取消隐藏',
		'results_for_x' => '^的搜索结果',
		'retagged' => '更改标签',
		'save_button' => '保存',
		'search_button' => '搜索',
		'search_explanation' => '请输入搜索内容重试。',
		'search_title' => '搜索结果',
		'selected' => '选中',
		'send_button' => '发送',
		'suggest_ask' => '获得帮助，从这里发起^1提问^2.',
		'suggest_category_qs' => '点击查看 ^分类^2 下的所有问题',
		'suggest_qs_tags' => '点击^1问题列表^2 或 ^3热门标签^4，查看更多内容。',
		'suggest_qs' => '点击^1问题列表^2，查看更多。',
		'unanswered_qs_in_x' => '^下最新待回答问题',
		'unanswered_qs_title' => '最新待回答问题',
		'unselected_qs_in_x' => '^下最新待解决的问题',
		'unselected_qs_title' => '尚未解决的问题',
		'unupvoteda_qs_in_x' => ' ^下无赞成票的问题',
		'unupvoteda_qs_title' => '最新无赞成票的问题',
		'upload_limit' => '太多上传 - 请稍后重试',
		'view_q_must_confirm' => '请^5确认邮件地址^6后查看问题页面.',
		'view_q_must_login' => '请^1登录^2或^3注册^4后查看问题页面.',
		'viewed_qs_in_x' => '^下最多浏览问题',
		'viewed_qs_title' => '浏览最多的问题',
		'vote_disabled_down' => '特定用户才能投反对票',
		'vote_disabled_hidden_a' => '不能对隐藏答案投票',
		'vote_disabled_hidden_q' => '不能对隐藏问题投票',
		'vote_disabled_level' => '特定用户才能投票',
		'vote_disabled_my_a' => '不能对自己的答案进行投票',
		'vote_disabled_my_q' => '不能对自己的问题进行投票',
		'vote_disabled_q_page_only' => '去问题页面投票',
		'vote_down_must_confirm' => '^5确认邮箱^6后投反对票',
		'vote_down_popup' => '点击投反对票',
		'vote_limit' => '投票失败 - 请稍候重试',
		'vote_must_confirm' => '^5确认邮箱^6后投票。',
		'vote_must_login' => '请^1l登录^2 或 ^3注册^4后投票',
		'vote_not_allowed' => '不允许投票',
		'vote_up_popup' => '点击投赞成票',
		'voted_down_popup' => '你对此问题投了反对票 - 点击删除头',
		'voted_qs_in_x' => '^投票最多问题',
		'voted_qs_title' => '投票最多问题',
		'voted_up_popup' => '投了赞成票- 点击删除',
		'x_ago' => '^前',
		'x_answers' => '^ 回复',
		'x_comments' => '^ 评论',
		'x_days' => '^ 天',
		'x_disliked' => '^ 不喜欢',
		'x_flags' => '^ 举报',
		'x_hours' => '^ 小时',
		'x_liked' => '^ 喜欢',
		'x_minutes' => '^ 分钟',
		'x_months' => '^ 月',
		'x_points' => '^ 基本',
		'x_questions' => '^ 问题',
		'x_seconds' => '^ 秒',
		'x_tags' => '^ 标签',
		'x_users' => '^ 用户',
		'x_views' => '^ 浏览',
		'x_votes' => '^ 投票',
		'x_weeks' => '^ 周',
		'x_years' => '^ 年',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
